Description of myupdatefcn
Home > TOSSH > example > functions > plotting > myupdatefcn.m
myupdatefcn
PURPOSE
Customizes text of data tips
SYNOPSIS
function txt = myupdatefcn(~,event_obj,ID,index)
DESCRIPTION
 Customizes text of data tips
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
makeScatterPlot makeScatterPlot Makes scatter plot to compare all CAMELS signatures.
plotMapUK plotMapUK Plots UK map with dots coloured according to an attribute.
plotMapUS plotMapUS Plots US map with dots coloured according to an attribute.
SOURCE CODE
function txt = myupdatefcn(~,event_obj,ID,index)
% Customizes text of data tips
pos = get(event_obj,'Position');
I = get(event_obj, 'DataIndex');
txt = {['X: ',num2str(pos(1))],...
    ['Y: ',num2str(pos(2))],...
    ['i: ',num2str(index(I))],...
    ['ID: ',num2str(ID(I))]};
end